In [1]:
import torch
import numpy as np


In [2]:
zeros1 = torch.zeros(size = (3,4,2,4,5))
print(zeros1.shape[:3])
zeros2 = torch.zeros(zeros1.shape[:3])
print(zeros2.shape)
tensor_to_pad = torch.Tensor([[1,2,3],[4,5,6]])
print(tensor_to_pad.shape)
tensor_to_pad = torch.unsqueeze(tensor_to_pad,dim=-1)
print(tensor_to_pad.shape)
print(tensor_to_pad)

torch.Size([3, 4, 2])
torch.Size([3, 4, 2])
torch.Size([2, 3])
torch.Size([2, 3, 1])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])


In [5]:
test = torch.Tensor([[1,2,3],[4,5,6]])
print(test.shape)
print(test.reshape(-1).shape)

test_factor = torch.Tensor([[2,3,4]])

print(test * test_factor)
total_time = 2.0
n_steps = 100
t_reverse_list = torch.linspace(total_time, 0, n_steps)


print(t_reverse_list)

torch.Size([2, 3])
torch.Size([6])
tensor([[ 2.,  6., 12.],
        [ 8., 15., 24.]])
tensor([2.0000, 1.9798, 1.9596, 1.9394, 1.9192, 1.8990, 1.8788, 1.8586, 1.8384,
        1.8182, 1.7980, 1.7778, 1.7576, 1.7374, 1.7172, 1.6970, 1.6768, 1.6566,
        1.6364, 1.6162, 1.5960, 1.5758, 1.5556, 1.5354, 1.5152, 1.4949, 1.4747,
        1.4545, 1.4343, 1.4141, 1.3939, 1.3737, 1.3535, 1.3333, 1.3131, 1.2929,
        1.2727, 1.2525, 1.2323, 1.2121, 1.1919, 1.1717, 1.1515, 1.1313, 1.1111,
        1.0909, 1.0707, 1.0505, 1.0303, 1.0101, 0.9899, 0.9697, 0.9495, 0.9293,
        0.9091, 0.8889, 0.8687, 0.8485, 0.8283, 0.8081, 0.7879, 0.7677, 0.7475,
        0.7273, 0.7071, 0.6869, 0.6667, 0.6465, 0.6263, 0.6061, 0.5859, 0.5657,
        0.5455, 0.5253, 0.5051, 0.4848, 0.4646, 0.4444, 0.4242, 0.4040, 0.3838,
        0.3636, 0.3434, 0.3232, 0.3030, 0.2828, 0.2626, 0.2424, 0.2222, 0.2020,
        0.1818, 0.1616, 0.1414, 0.1212, 0.1010, 0.0808, 0.0606, 0.0404, 0.0202,
        0.0000])
